### ISSUE TITLE
Let altair2fasthtml() accept kwargs to be passed on as options to the eventual vegaEmbed call

### ISSUE THREAD

**Issue by ddanieltan** [koaning/fh-altair#8]
vegaEmbed takes in a variety of options [docs](https://github.com/vega/vega-embed?tab=readme-ov-file#options). I suggest adding a kwarg into `altair2fasthtml()` arguments that get passed on to the eventual vegaEmbed call.

Rough mock
```python
def altair2fasthtml(chart, user_options):
    jsonstr = chart.to_json()
    chart_id = f'uniq-{uuid4()}'
    default_options = {"actions": "false"}
    options = {**user_options, **default_options}
    return Div(Script(f"vegaEmbed('#{chart_id}', {jsonstr}, {options});"), id=chart_id)
```

I'd be happy to submit a PR if you like this idea.

**Comment by koaning** [comment]
As long as it is easy to find the kwargs then it could be fine. The annoying thing with kwargs sometimes is that you pass on a lot of responsibility to the end user. If one is not familiar with vega, then it can be intimidating to find the right setting. 

That said, it can also open up a lot of options to those who know what they are doing. 

Before making a PR though, what are you trying to fix with the kwargs? It might be worth highlighting explicitly in the readme.

**Comment by ddanieltan** [comment]
Thanks for the quick feedback, all fair points.

Re: designing kwargs for power users without intimidating newer users, how about using an optional kwargs pattern like so?
```python
def altair2fasthtml(chart, **kwargs):
     if kwargs:
          # optional vegaEmbed params passed on
          ...
    # regular logic
    ...
```

Re: highlighting explicitly the benefits of kwargs in the README
I plan to add examples for:
- rendering chart as an svg instead of a canvas by passing in `renderer` option (this was my original use case)
- removing action links ("Export as PNG/SVG", "View Source", "View Vega" etc) in the rendered plot via the `actions` option

I believe these are tweaks that can only be done during the `vegaEmbed` call.

There are other tweakable options such as `width`, `height`, `tooltips` but as there are native methods to manipulate these in Altair, I think it's better to leave these out as examples. I think users are better served tweaking those fields directly in Altair.

**Comment by koaning** [comment]
Do the action links render on your end? I recall trying to automatically turning that off as a default. But yeah, that could indeed be a nice example of a kwarg.

**Comment by ddanieltan** [comment]
Oops, yes, action links are disabled by default right now as `actions: false` is currently the default option in `altair2fasthtml()`. 
Perhaps I should change the README entry with an example to include action links instead of removing action links (which I agree should be the default).
